name: it_company_name_generator
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.1
  hydrated_bloc: ^7.0.1
  replay_bloc: ^0.0.2
  equatable: ^2.0.3
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
  errors:
    mixin_inherits_from_not_object: ignore

