name: it_company_name_generator
description: a joke application to help it company choose the name
publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # needed for settings_model
  equatable: ^2.0.3
  path_provider: ^2.0.2
  flutter_bloc: ^7.0.1
  hydrated_bloc: ^7.0.1
  replay_bloc: ^0.0.2

  #needed for generation_model
  provider: ^5.0.0

  # one-liner for navigator animation
  proste_route_animation: ^2.0.2

  # to show animated spinkin when data not generated
  flutter_spinkit: ^5.0.0

flutter:
  uses-material-design: true

